### Create a Gift Card
POST http://localhost:4500/api/giftcards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2ZlNDUwYTBiOTY1Yjg4YjNmZTc5YmMiLCJuYW1lIjoiVWdvY2h1a3d1IE1lc2hhY2giLCJlbWFpbCI6InVnb2NodWt3dW1lc2hhY2g4QGdtYWlsLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTc1NDE4NTgzOSwiZXhwIjoxNzU0MTg5NDM5fQ.YFGBxrrqtecicmG74MyTlQoAucwINPJSiLaKjk2p61w
Content-Type: application/json

{
  "name": "Razer Gold Pin",
  "brand": "Razer",
  "value": 1270,
  "currency": "USD",
  "image": "https://res.cloudinary.com/drbiup2zg/image/upload/v1742984827/razer_kqt8dh.webp"
}


### get giftcard
GET http://localhost:4500/api/admin/redemptions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODhjNDJiM2M3MjkzODAzMGQ4NGUyYzIiLCJuYW1lIjoiVWdvY2h1a3d1IE1lc2hhY2giLCJlbWFpbCI6InVnb2J1ZXpld2ViQGdtYWlsLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTc1NDIwMDQwMiwiZXhwIjoxNzU0MjA0MDAyfQ.h4kPk-dNMqZRqTL6fvvWiouk_TvjlzVrSyVJvQ2wCb0

### Accept giftcard
POST  http://localhost:4500/api/admin/redemptions/688edcc0fe2924a67240de33/approve
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2ZlNDUwYTBiOTY1Yjg4YjNmZTc5YmMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NTQxOTIwMzUsImV4cCI6MTc1NDE5NTYzNX0.l6ogXWuYKQcx2iyl08s54bCyHVEuWl4svJf-h7dsTLw
Content-Type: application/json


### Reject giftcard
POST  http://localhost:3500/api/admin/redemptions/67ec33f154e4c1a5b4d09b2a/reject
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2UzYzE0ZTMyNDBlYWQzNDNlNzM5MWQiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NDQ1NTgzNTYsImV4cCI6MTc0NDU2MTk1Nn0.ZlleMpNaPNisXHVQvejNkO5u6l0PLbhy8jM3YNmTfTc
Content-Type: application/json

### Reason
POST  http://localhost:3500/api/admin/redemptions/67ec33f154e4c1a5b4d09b2a/reject
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2UzYzE0ZTMyNDBlYWQzNDNlNzM5MWQiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NDQ1NDM5NzQsImV4cCI6MTc0NDU0NzU3NH0.h_Wx5FZr9Y1b5epd4ZbetoBprKPebyiSKj1AkrvrEbY
Content-Type: application/json

{
  "reason": "Card image is blurry"
}

### Create a Referral
POST http://localhost:4500/api/referrals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2ZlNDUwYTBiOTY1Yjg4YjNmZTc5YmMiLCJuYW1lIjoiVWdvY2h1a3d1IE1lc2hhY2giLCJlbWFpbCI6InVnb2NodWt3dW1lc2hhY2g4QGdtYWlsLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTc1NDAyMDUzMywiZXhwIjoxNzU0MDI0MTMzfQ.yWBiZ7gncB4lzpZ5-0iNPXHAURi7T_gn4ravqD1ZkPI
Content-Type: application/json

{
  "referrerCode": "REF123ABC",
  "referredUserId": "64d1f9f5d9c0ab1234567890"
}

### create user
POST http://localhost:4500/api/users
Content-Type: application/json

{
  "name": "Charlotte Davis",
  "email": "charlottedavis333@gmail.com",
  "password": "Askme@330",
  "referredBy": "-Og1mR-d"
}

### Get User Details
GET http://localhost:4500/api/users/me
Authorization: Bearer   eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI6ODhjNDJiM3M3MjkzODAzMGQ4NGUyYzIiLCJuYW1lIjoiVWdvY2h1a3d1IE1lc2hhY2giLCJlbWFpbCI6InVnb2J1ZXpld2ViQGdtYWlsLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTc1NDI1MzA2NiwiZXhwIjoxNzU0MjU2NjY2fQ.pUmeDfOAw7KQHdHBH5d2V51JsNsJRV-4KN3QBkQaxFQ


### Get User Referrals
GET http://localhost:4500/api/user/referrals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODhjNDJiM2M3MjkzODAzMGQ4NGUyYzIiLCJuYW1lIjoiVWdvY2h1a3d1IE1lc2hhY2giLCJlbWFpbCI6InVnb2J1ZXpld2ViQGdtYWlsLmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3NTQwMjgxNjksImV4cCI6MTc1NDAzMTc2OX0._aykb0MrQd3kg2nNC9PRM3JVETNHMf066Mn_gptFBek

### Get Referral Leaderboard
GET http://localhost:4500/api/referrals/leaderboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI6ODhjNDJiM3M3MjkzODAzMGQ4NGUyYzIiLCJuYW1lIjoiVWdvY2h1a3d1IE1lc2hhY2giLCJlbWFpbCI6InVnb2J1ZXpld2ViQGdtYWlsLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTc1NDI1MzA2NiwiZXhwIjoxNzU0MjU2NjY2fQ.pUmeDfOAw7KQHdHBH5d2V51JsNsJRV-4KN3QBkQaxFQ

### Get Referral Stats
GET http://localhost:4500/api/referrals/stats/-Og1mR-d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI6ODhjNDJiM3M3MjkzODAzMGQ4NGUyYzIiLCJuYW1lIjoiVWdvY2h1a3d1IE1lc2hhY2giLCJlbWFpbCI6InVnb2J1ZXpld2ViQGdtYWlsLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTc1NDI1MzA2NiwiZXhwIjoxNzU0MjU2NjY2fQ.pUmeDfOAw7KQHdHBH5d2V51JsNsJRV-4KN3QBkQaxFQ

### Redeem Referral
PATCH http://localhost:4500/api/referrals/redeem
Content-Type: application/json

{
  "referredUserId": "688c5c4f101edb91048fd52b"
}

#### Redeem Referral
PATCH http://localhost:4500/api/referrals/redeem
Content-Type: application/json

{
  "referredUserId": "688c54ee94ea23e3e0c1f3d1"
}


### Get Referral Code
GET http://localhost:4500/api/referrals/code/688e3589db1879cc605b6737
Content-Type: application/json

### 1. Admin Login
POST http://localhost:4500/api/auth/loginnow
Content-Type: application/json

{
  "email": "ugobuezeweb@gmail.com",
  "password": "ugobueze"
}

### 2. Get All Gift Cards
GET http://localhost:4500/api/giftcards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2ZlNDUwYTBiOTY1Yjg4YjNmZTc5YmMiLCJuYW1lIjoiVWdvY2h1a3d1IE1lc2hhY2giLCJlbWFpbCI6InVnb2NodWt3dW1lc2hhY2g4QGdtYWlsLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTc1NDEwMTQwNSwiZXhwIjoxNzU0MTA1MDA1fQ.vAcjg7DAfDyclnSevRjSXItAXc8VxRhM8AoffoVp0ME

### 3. Create Gift Card (Admin)
POST http://localhost:4500/api/giftcards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2ZlNDUwYTBiOTY1Yjg4YjNmZTc5YmMiLCJuYW1lIjoiVWdvY2h1a3d1IE1lc2hhY2giLCJlbWFpbCI6InVnb2NodWt3dW1lc2hhY2g4QGdtYWlsLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTc1NDA5ODg3NiwiZXhwIjoxNzU0MTAyNDc2fQ.VPRmCdZBa7SfVYbCqaXC57QO8Gnyw2LzJenTc6ZnwZU
Content-Type: application/json

{
  "name": "Amazon $50",
  "brand": "Amazon",
  "value": 150,
  "currency": "USD",
  "image": "https://res.cloudinary.com/drbiup2zg/image/upload/v1742984827/razer_kqt8dh.webp"
}

### 5. Get All Redemptions (Admin)

GET http://localhost:4500/api/admin/redemptions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OTFjNjZmODcxZmVlZjJkZTRkMTA0OCIsImVtYWlsIjoidWdvYnVlemV3ZWI1MDVAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU0MzgzOTg0LCJleHAiOjE3NTQ5ODg3ODR9.9YIOZRGGzDZiWgVhhb9JWm00G9NqLlkVne9B7M05evg





### User Login
POST http://localhost:4500/api/auth/loginnow
Content-Type: application/json

{
  "email": "ugobuezewebstudio@gmail.com",
  "password": "ugobueze"
}


### Create User
POST http://localhost:4500/api/users
Content-Type: application/json

{
  "name": "Ugo web studio",
  "email": "ugobuezewebstudio@gmail.com",
  "password": "ugobueze",
  "referredBy": "-Og1mR-d",
  "isAdmin": true
}
